Repository hardbyte/python-can, pull requests merged in 2018-07, with the labels that each got.

#346 Add coverage report generation
  .appveyor.yml
  .travis.yml
  can/interfaces/ics_neovi/neovi_bus.py
  setup.py
Labels: testing

#338 Enable support for non default config section
  can/interface.py
  can/util.py
  doc/configuration.rst
  test/test_load_file_config.py
Labels: api, enhancement

#347 Fix Sphinx errors/warnings & Misc. cleanups
  can/broadcastmanager.py
  can/bus.py
  can/interfaces/iscan.py
  can/interfaces/pcan/basic.py
  can/interfaces/pcan/pcan.py
  can/util.py
  doc/bcm.rst
  doc/bus.rst
  doc/conf.py
  doc/development.rst
  doc/interfaces/serial.rst
  doc/listeners.rst
  examples/cyclic.py
Labels: docs

#362 Implement _detect_available_configs for Vector
  can/interfaces/vector/canlib.py
  can/interfaces/vector/vxlapi.py
Labels: backend:vector, enhancement

#364 NI-CAN: Add reset method and remove flush_tx_buffer method
  can/interfaces/nican.py
Labels: backend:nican

#367 Misc cleanups
  can/CAN.py
  can/bus.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/slcan.py
  can/interfaces/usb2can/serial_selector.py
  can/io/asc.py
  can/notifier.py
  can/thread_safe_bus.py
  doc/bus.rst
  doc/development.rst
  doc/interfaces/ixxat.rst
  doc/interfaces/slcan.rst
Labels: docs, minor

#368 Syntax highlighting for the example code in README.rst
  README.rst
Labels: docs, minor

#371 Add classifiers to setup.py
  setup.py
Labels: docs, minor

#370 New location for scripts
  .appveyor.yml
  .travis.yml
  README.rst
  can/__init__.py
  can/scripts/__init__.py
  can/scripts/logger.py
  can/scripts/player.py
  doc/development.rst
  doc/index.rst
  doc/scripts.rst
  scripts/can_logger.py
  scripts/can_player.py
  setup.cfg
  setup.py
Labels: api, docs, minor, testing

#373 virtual_can_demo.py changes
  examples/virtual_can_demo.py
Labels: docs, minor

#374 Add a .codecov.yml
  .codecov.yml
  README.rst
Labels: testing
