Repository hardbyte/python-can, pull requests merged in 2018-03, with the labels that each got.

#275 Added proof-of-concept testing of SocketCAN on Travis CI & Smaller changes
  .appveyor.yml
  .travis.yml
  can/interfaces/virtual.py
  can/io/logger.py
  can/io/player.py
  requirements.txt
  setup.py
  test/back2back_test.py
  test/config.py
  test/data/example_data.py
  test/listener_test.py
  test/network_test.py
  test/open_vcan.sh
  test/simplecyclic_test.py
Labels: testing

#266 can.Notifier enhancements
  can/notifier.py
  test/back2back_test.py
  test/listener_test.py
  test/logformats_test.py
Labels: api

#276 Remove `load_default_settings` call in init
  can/interfaces/ics_neovi/neovi_bus.py
Labels: bug

#281 Updated PCAN interface
  can/interfaces/pcan/PCANBasic.py
Labels: backend:pcan, enhancement
