Repository hardbyte/python-can, pull requests merged in 2018-09, with the labels that each got.

#402 Add hardware handshake support for serial port based CAN interfaces
  can/interfaces/serial/serial_can.py
  can/interfaces/slcan.py
Labels: api, backend:serial, enhancement

#405 Leave a note on the OSX support in .travis.yml
  .travis.yml
Labels: minor, os:osx, testing

#388 Add asyncio support
  can/__init__.py
  can/interfaces/serial/serial_can.py
  can/interfaces/slcan.py
  can/interfaces/socketcan/socketcan.py
  can/listener.py
  can/notifier.py
  doc/api.rst
  doc/asyncio.rst
  doc/listeners.rst
  examples/asyncio_demo.py
  test/notifier_test.py
Labels: api, enhancement

#407 Allow user to choose channel using ICS network names
  can/interfaces/ics_neovi/neovi_bus.py
Labels: api, enhancement, minor

#406 Fix location of scripts
  .appveyor.yml
  can/__init__.py
  can/interface.py
  can/logger.py
  can/player.py
  can/scripts/__init__.py
  doc/scripts.rst
  scripts/can_logger.py
  scripts/can_player.py
  setup.cfg
  test/test_detect_available_configs.py
  test/test_scripts.py
Labels: bug, minor, testing

#411 Message dlc alignment in string representation
  can/message.py
Labels: minor

#408 Adding ICS CAN FD support
  can/interfaces/ics_neovi/neovi_bus.py
Labels: api, backend:neovi, enhancement

#390 Merge the CAN viewer terminal application into python-can
  .gitignore
  CONTRIBUTORS.txt
  can/viewer.py
  doc/history.rst
  doc/images/viewer.png
  doc/scripts.rst
  scripts/can_viewer.py
  setup.py
  test/test_viewer.py
Labels: api, enhancement, major

#420 Fix permissions and shebangs in examples
  examples/receive_all.py
  examples/serial_com.py
  examples/vcan_filtered.py
  examples/virtual_can_demo.py
Labels: minor

#417 Fix for numbered windows config file list documentation
  doc/configuration.rst
Labels: docs, minor

#415 Adding multiple channels support to neoVI
  can/interfaces/ics_neovi/neovi_bus.py
Labels: backend:neovi, enhancement

#412 Feature socketcan bcm owned by bus
  .codecov.yml
  can/bus.py
  can/interfaces/socketcan/socketcan.py
  doc/bcm.rst
  doc/bus.rst
  test/simplecyclic_test.py
Labels: bug

#426 Separate interface and implementation for periodic sending
  can/broadcastmanager.py
  can/bus.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/socketcan/socketcan.py
  doc/development.rst
  examples/cyclic.py
Labels: api, docs, minor

#428 Extract cli help automatically
  .travis.yml
  doc/bus.rst
  doc/conf.py
  doc/development.rst
  doc/doc-requirements.txt
  doc/scripts.rst
Labels: docs, minor

#432 Remove spaces from setup.py version specifiers
  setup.py
Labels: bug, minor

#413 Change can.Message
  .codecov.yml
  can/CAN.py
  can/broadcastmanager.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/kvaser/canlib.py
  can/interfaces/nican.py
  can/interfaces/pcan/pcan.py
  can/interfaces/usb2can/usb2canInterface.py
  can/interfaces/vector/canlib.py
  can/io/blf.py
  can/io/csv.py
  can/io/sqlite.py
  can/message.py
  doc/bcm.rst
  doc/development.rst
  doc/listeners.rst
  doc/message.rst
  setup.py
  test/back2back_test.py
  test/data/example_data.py
  test/logformats_test.py
  test/message_helper.py
  test/network_test.py
  test/serial_test.py
  test/simplecyclic_test.py
  test/test_detect_available_configs.py
  test/test_kvaser.py
Labels: api, bug
