Repository hardbyte/python-can, pull requests merged in 2018-10, with the labels that each got.

#447 Fix some slcan issues
  can/interfaces/slcan.py
  test/test_slcan.py
Labels: backend:serial

#452 Make typing dependency conditional < python 3.5
  setup.py
Labels: minor

#454 Doc update for socketcan
  doc/interfaces/socketcan.rst
Labels: docs, minor

#456 Fixed license header
  can/viewer.py
  test/test_viewer.py
Labels: minor
