Repository hardbyte/python-can, pull requests merged in 2019-02, with the labels that each got.

#501 Fully initialize usb2can Bus interface object.
  can/interfaces/usb2can/usb2canInterface.py
  doc/interfaces/usb2can.rst
Labels: backend:usb2can, bug

#497 Message class changes
  can/message.py
  setup.py
  test/data/example_data.py
  test/message_helper.py
  test/notifier_test.py
  test/test_message_class.py
Labels: api, testing, work-in-progress

#508 Update iscan.py
  can/interfaces/iscan.py
Labels: enhancement

#514 Fix #510: Do only case insensitive matches in ASCReader
  can/io/asc.py
Labels: bug

#527 Update Badges in Readme
  README.rst
Labels: minor

#526 Include all test scripts in manifest.
  MANIFEST.in
Labels: testing
