Repository hardbyte/python-can, pull requests merged in 2019-06, with the labels that each got.

#612 Add wrongly removed statement back to codebase
  can/interfaces/kvaser/canlib.py
Labels: bug

#611 Slcan review
  can/interfaces/slcan.py
  test/test_slcan.py
Labels: api, backend:serial, enhancement

#619 Add badge for black
  README.rst
Labels: docs, minor

#622 Remove Travis builds of Python 3.7 & nightly on OSX
  .travis.yml
Labels: QA, testing

#621 Use inter-process mutex to prevent concurrent neoVI device open
  can/interfaces/ics_neovi/neovi_bus.py
  setup.py
Labels: backend:neovi, enhancement

#624 Update Readme: 4.x is currently developed
  README.rst
Labels: docs

#567 adding seeedstudio usb-can-analyzer interface
  can/interfaces/__init__.py
  can/interfaces/seeedstudio/__init__.py
  can/interfaces/seeedstudio/seeedstudio.py
  doc/interfaces/seeedstudio.rst
  setup.py
Labels: api, enhancement, major

#615 Add bit timing class
  can/__init__.py
  can/bit_timing.py
  can/util.py
  doc/api.rst
  doc/bit_timing.rst
  test/test_bit_timing.py
Labels: api, enhancement

#628 Avoid padding CAN_FD_MESSAGE_64 objects to 4 bytes
  can/io/blf.py
Labels: bug, file-io

#626 More flexible configuration context handling and allow CAN_CONFIG env var
  can/util.py
  doc/configuration.rst
  test/test_load_file_config.py
Labels: api, enhancement
