Repository hardbyte/python-can, pull requests merged in 2019-04, with the labels that each got.

#540 Fixed simplecyclic test
  test/simplecyclic_test.py
Labels: minor, testing

#546 Fix Dead Link
  examples/send_one.py
Labels: docs, minor

#547 Fix typos & add docs
  can/message.py
Labels: minor

#550 Direct setup.py test to use pytest. (Addresses Issue #544)
  setup.cfg
  setup.py
Labels: testing

#548 Add guide for new io formats
  can/io/__init__.py
  doc/development.rst
  doc/internal-api.rst
Labels: docs

#533 Turn BusState into an enum
  can/bus.py
  can/interfaces/pcan/pcan.py
  can/interfaces/systec/ucanbus.py
  can/logger.py
  examples/receive_all.py
  setup.py
Labels: api

#537 implemented FD for Pcan
  can/interfaces/pcan/pcan.py
Labels: backend:pcan, enhancement

#553 Add availability to set can custom speed in slcan backend
  can/interfaces/slcan.py
Labels: backend:serial, enhancement, minor
