Repository hardbyte/python-can, pull requests merged in 2019-05, with the labels that each got.

#559 Add missing step to the new IO docs
  doc/internal-api.rst
Labels: docs, minor

#558 Fix broken execution of tests on some Windows environments
  test/logformats_test.py
  test/test_scripts.py
Labels: bug, testing

#561 Test MessageSync
  can/io/player.py
  test/logformats_test.py
  test/message_helper.py
  test/simplecyclic_test.py
  test/test_message_sync.py
Labels: testing

#572 Various spelling corrections in the generated docs
  README.rst
  can/interfaces/virtual.py
  can/io/csv.py
  can/io/printer.py
  can/io/sqlite.py
  can/notifier.py
  doc/interfaces/ixxat.rst
  doc/interfaces/nican.rst
  test/back2back_test.py
Labels: docs, minor

#569 Make coverage collection slightly faster
  .appveyor.yml
  .travis.yml
Labels: minor, testing

#571 Fix deprecated constructor call
  can/interfaces/systec/ucanbus.py
Labels: backend:systec, minor

#573 Fix stuct packing in build_bcm_header on 32-bit
  can/interfaces/socketcan/socketcan.py
  test/test_socketcan.py
Labels: backend:socketcan, bug

#568 Adding CAN FD 64 frame support to blf reader
  can/io/blf.py
Labels: enhancement, file-io

#590 Add additional coverage to SocketCAN interface
  test/test_socketcan.py
Labels: backend:socketcan, os:linux, testing

#592 Enable pylint on Travis CI builds
  .pylintrc
  .pylintrc-wip
  .travis.yml
  requirements-lint.txt
Labels: QA

#562 General exception handling (+ changes to the ixxat interface)
  can/__init__.py
  can/exceptions.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/ixxat/exceptions.py
  doc/api.rst
  setup.py
  test/test_interface_ixxat.py
Labels: api, enhancement

#596 Modernize all the test cases
  setup.py
  test/back2back_test.py
  test/listener_test.py
  test/logformats_test.py
  test/message_helper.py
  test/network_test.py
  test/notifier_test.py
  test/serial_test.py
  test/simplecyclic_test.py
  test/test_detect_available_configs.py
  test/test_kvaser.py
  test/test_load_file_config.py
  test/test_message_filtering.py
  test/test_message_sync.py
  test/test_scripts.py
  test/test_slcan.py
  test/test_socketcan.py
  test/test_socketcan_helpers.py
  test/test_systec.py
  test/test_viewer.py
Labels: major, testing

#570 Fix warning in usb2can
  can/interfaces/usb2can/serial_selector.py
Labels: backend:usb2can, bug, minor

#601 Remove some linter exclusions
  .pylintrc-wip
  can/__init__.py
  can/broadcastmanager.py
  can/bus.py
  can/ctypesutil.py
  can/interface.py
  can/interfaces/ics_neovi/neovi_bus.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/ixxat/exceptions.py
  can/interfaces/kvaser/canlib.py
  can/interfaces/nican.py
  can/interfaces/pcan/basic.py
  can/interfaces/pcan/pcan.py
  can/interfaces/serial/serial_can.py
  can/interfaces/socketcan/socketcan.py
  can/interfaces/socketcan/utils.py
  can/interfaces/systec/exceptions.py
  can/interfaces/systec/structures.py
  can/interfaces/systec/ucan.py
  can/interfaces/systec/ucanbus.py
  can/interfaces/usb2can/serial_selector.py
  can/interfaces/usb2can/usb2canInterface.py
  can/interfaces/usb2can/usb2canabstractionlayer.py
  can/interfaces/vector/canlib.py
  can/interfaces/vector/vxlapi.py
  can/io/blf.py
  can/io/canutils.py
  can/io/csv.py
  can/io/generic.py
  can/io/logger.py
  can/io/sqlite.py
  can/listener.py
  can/logger.py
  can/message.py
  can/thread_safe_bus.py
  can/util.py
  can/viewer.py
Labels: QA
