Repository hardbyte/python-can, pull requests merged in 2019-08, with the labels that each got.

#658 Add typing annotations for can.broadcastmanager
  .travis.yml
  can/broadcastmanager.py
  can/bus.py
  can/typechecking.py
Labels: QA

#664 Add typing annotations for can.message
  can/message.py
  can/typechecking.py
Labels: QA

#665 Add RedirectReader to the generated Listener docs
  doc/listeners.rst
Labels: docs

#667 State "windows only" in Vector docs
  can/interfaces/vector/canlib.py
  doc/interfaces/vector.rst
  test/test_vector.py
Labels: backend:vector, docs

#659 PCAN: Do not incorrectly reset CANMsg.MSGTYPE on remote frame.
  can/interfaces/pcan/pcan.py
Labels: backend:pcan, bug

#656 Make ThreadBasedCyclicSendTask event based
  can/broadcastmanager.py
  setup.py
Labels: enhancement, os:windows

#669 Add the seeedstudio interface to docs
  doc/interfaces.rst
Labels: docs

#675 Add typing annotations for can.listener
  can/broadcastmanager.py
  can/bus.py
  can/listener.py
Labels: QA

#672 Add .mypy_cache to gitignore file
  .gitignore
Labels: minor

#689 Update Readme
  README.rst
Labels: docs, minor
