Repository hardbyte/python-can, pull requests merged in 2019-09, with the labels that each got.

#691 Fix bitrate setting in slcan
  can/interfaces/slcan.py
Labels: bug

#690 Ignore error frames in can.player by default
  can/player.py
Labels: enhancement

#674 Add typing annotations for can.util
  can/typechecking.py
  can/util.py
Labels: QA
