Repository hardbyte/python-can, pull requests merged in 2020-11, with the labels that each got.

#917 Vector: Add more interface information to channel config
  can/interfaces/vector/canlib.py
  can/interfaces/vector/xldefine.py
  test/test_vector.py
Labels: backend:vector, bug, enhancement

#939 Update PCAN docs
  doc/interfaces/pcan.rst
Labels: backend:pcan, docs, minor

#924 Slcan: fix fileno issue with windows
  can/interfaces/slcan.py
Labels: api, bug

#943 Move "filelock" to neovi dependencies
  setup.py
Labels: QA

#945 removes setuptools from install requires
  setup.py
Labels: docs, minor

#705 Add Travis CI support for arm64 architectures
  .travis.yml
Labels: QA
