Repository hardbyte/python-can, pull requests merged in 2020-08, with the labels that each got.

#853 CANtact Support
  can/interfaces/__init__.py
  can/interfaces/cantact.py
  doc/installation.rst
  setup.py
  test/simplecyclic_test.py
  test/test_cantact.py
Labels: work-in-progress

#880 Use IntEnum for vector
  can/bus.py
  can/interfaces/vector/canlib.py
  can/interfaces/vector/xldefine.py
  setup.py
Labels: QA

#788 Fix issue with extended_id=None in 3.3.X release
  can/message.py
Labels: backport
