Repository hardbyte/python-can, pull requests merged in 2021-07, with the labels that each got.

#1098 Update docstring of can.io.generic.FileIOMessageWriter
  can/io/generic.py
Labels: docs, minor

#1040 Log suppressed error in notifier
  can/listener.py
  can/notifier.py
Labels: api, bug

#1107 Mark CAN FD support as tested
  test/logformats_test.py
Labels: QA

#1108 Mention buffer sizes in socketcan docs
  doc/interfaces/socketcan.rst
Labels: backend:socketcan, docs

#1100 Specific Exceptions: Adapting nican interface (+ add some typing)
  can/interfaces/nican.py
Labels: backend:nican, enhancement

#1099 Removes an unneeded line from the two scripts; Use context manager in player.py
  can/logger.py
  can/player.py
Labels: QA, minor

#1090 Specific Exceptions: Adapting seeedstudio interface
  can/interfaces/seeedstudio/seeedstudio.py
Labels: backend:seeedstudio, enhancement

#1091 Specific Exceptions: Adapting usb2can interface (+ simplify + partially type)
  can/interfaces/usb2can/serial_selector.py
  can/interfaces/usb2can/usb2canInterface.py
  can/interfaces/usb2can/usb2canabstractionlayer.py
Labels: backend:usb2can, enhancement

#1069 Test on 3.10.0-beta.2
  .github/workflows/build.yml
  tox.ini
Labels: testing
