Repository hardbyte/python-can, pull requests merged in 2021-11, with the labels that each got.

#1148 Tiny: Fix the way CI status conditions are specified for Mergify
  .mergify.yml
Labels: QA

#1149 Tiny: Update development.rst
  doc/development.rst
Labels: docs

#1147 Improve IO class hierarchy + Allow to use SizedRotatingLogger as a context manager
  can/io/asc.py
  can/io/blf.py
  can/io/canutils.py
  can/io/csv.py
  can/io/generic.py
  can/io/logger.py
  can/io/printer.py
  can/typechecking.py
  test/test_rotating_loggers.py
  tox.ini
Labels: bug, enhancement, api, file-io, QA

#1158 Specific Exceptions: Adapting systec interface
  can/interfaces/systec/__init__.py
  can/interfaces/systec/exceptions.py
  can/interfaces/systec/ucan.py
  can/interfaces/systec/ucanbus.py
  test/test_systec.py
Labels: backend:systec

#1156 Specific Exceptions: Adapting slcan interface
  can/interfaces/slcan.py
Labels: api, work-in-progress

#1167 Fix formatter and bump ci tools
  can/__init__.py
  can/interfaces/canalystii.py
  can/interfaces/cantact.py
  can/interfaces/ics_neovi/neovi_bus.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/ixxat/exceptions.py
  can/interfaces/kvaser/canlib.py
  can/interfaces/neousys/neousys.py
  can/interfaces/nixnet.py
  can/interfaces/seeedstudio/seeedstudio.py
  can/interfaces/socketcan/utils.py
  can/interfaces/systec/structures.py
  can/interfaces/udp_multicast/bus.py
  can/interfaces/vector/canlib.py
  can/interfaces/virtual.py
  can/io/asc.py
  can/io/blf.py
  can/io/generic.py
  can/io/logger.py
  can/io/sqlite.py
  can/listener.py
  can/message.py
  can/notifier.py
  can/util.py
  can/viewer.py
  doc/conf.py
  examples/serial_com.py
  requirements-lint.txt
  setup.py
  test/test_socketcan_loopback.py
Labels: QA

#1159 Add changed byte highlighting to viewer.py
  can/viewer.py
  doc/images/viewer_changed_bytes_highlighting.png
  doc/scripts.rst
  test/test_viewer.py
Labels: bug, enhancement

#1168 Specific Exceptions: Adapting gs_usb
  can/interfaces/gs_usb.py
Labels: api

#1166 Complete broken PR #1156 (Specific Exceptions: Adapting slcan interface)
  can/interfaces/slcan.py
  test/test_rotating_loggers.py
Labels: api, docs

#1170 Allowing for extra config arguments in can.logger
  can/logger.py
  can/viewer.py
  test/test_viewer.py
Labels: enhancement

#1173 Updating neoVI documentation and docstrings
  can/interfaces/ics_neovi/neovi_bus.py
  doc/interfaces/neovi.rst
Labels: docs, backend:neovi

#1174 Calling stop_all_periodic_tasks() in BusABC
  can/bus.py
  can/interfaces/canalystii.py
  can/interfaces/cantact.py
  can/interfaces/gs_usb.py
  can/interfaces/iscan.py
  can/interfaces/kvaser/canlib.py
  can/interfaces/neousys/neousys.py
  can/interfaces/nican.py
  can/interfaces/nixnet.py
  can/interfaces/robotell.py
  can/interfaces/seeedstudio/seeedstudio.py
  can/interfaces/serial/serial_can.py
  can/interfaces/slcan.py
  can/interfaces/socketcan/socketcan.py
  can/interfaces/systec/ucanbus.py
  can/interfaces/udp_multicast/bus.py
  can/interfaces/usb2can/usb2canInterface.py
  can/interfaces/vector/canlib.py
  can/interfaces/virtual.py
Labels: bug, api

#1138 Adding support for gzipped ASC logging file (.asc.gz)
  can/__init__.py
  can/io/__init__.py
  can/io/asc.py
  can/io/logger.py
  can/io/player.py
  test/logformats_test.py
Labels: enhancement, file-io
