Repository hardbyte/python-can, pull requests merged in 2021-12, with the labels that each got.

#1178 Improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: minor

#1072 Add logconvert script
  can/logconvert.py
  scripts/can_logconvert.py
  test/test_scripts.py
Labels: enhancement, file-io

#1128 add socketcan parameter to ignore CAN error frames
  can/interfaces/socketcan/socketcan.py
Labels: enhancement, api, backend:socketcan

#1140 socketcand Backend for python-can
  can/interfaces/__init__.py
  can/interfaces/socketcand/__init__.py
  can/interfaces/socketcand/socketcand.py
  doc/interfaces/socketcand.rst
Labels: enhancement, os:linux

#1119 Ixxat CAN FD support
  CONTRIBUTORS.txt
  can/interfaces/ixxat/__init__.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/ixxat/canlib_vcinpl.py
  can/interfaces/ixxat/canlib_vcinpl2.py
  can/interfaces/ixxat/constants.py
  can/interfaces/ixxat/structures.py
  doc/interfaces/ixxat.rst
  test/test_interface_ixxat.py
  test/test_interface_ixxat_fd.py
Labels: enhancement, backend:ixxat

#1152 Specific Exceptions: Adapting pcan interface
  can/interfaces/pcan/basic.py
  can/interfaces/pcan/pcan.py
  test/test_pcan.py
Labels: backend:pcan, api, docs

#1181 Raise ValueError if message data if over max frame length
  can/interfaces/ics_neovi/neovi_bus.py
Labels: bug, backend:neovi

#1182 [Tiny] Fix broken link in README
  README.rst
Labels: docs

#1184 Fix error with VN8900
  can/interfaces/vector/xldefine.py
Labels: bug, backend:vector

#1187 Fix spell error `touple` to `tuple`
  can/interfaces/pcan/basic.py
Labels: minor, docs

#1154 Specific Exceptions: Adapting nixnet interface
  can/interfaces/nixnet.py
Labels: enhancement, api, backend:nixnet

#1155 Specific Exceptions: Adapting robotell interface
  can/interfaces/robotell.py
Labels: api

#1144 Add ETAS interface
  CONTRIBUTORS.txt
  can/interfaces/__init__.py
  can/interfaces/etas/__init__.py
  can/interfaces/etas/boa.py
  doc/interfaces.rst
  doc/interfaces/etas.rst
  test/back2back_test.py
Labels: enhancement

#1189 Setting is_error_frame message property in neovi interface
  can/interfaces/ics_neovi/neovi_bus.py
Labels: enhancement, backend:neovi

#1194 Add can.logconvert to script docs
  doc/scripts.rst
Labels: docs
