Repository hardbyte/python-can, pull requests merged in 2021-06, with the labels that each got.

#1061 Fix CI timeout
  tox.ini
Labels: testing

#1067 Fix single typo
  can/io/generic.py
Labels: minor

#1052 Fix VectorError bug
  can/interfaces/vector/exceptions.py
  test/test_vector.py
Labels: backend:vector, blocker, bug

#1062 Preserve capitalization when reading config files
  can/util.py
Labels: bug

#1056 add tests for PCAN
  test/test_pcan.py
  tox.ini
Labels: backend:pcan, testing

#1068 Improve IO module typing
  can/io/generic.py
  can/typechecking.py
  examples/simple_log_converter.py
  setup.py
Labels: file-io, minor

#1075 Remove remaining encoding comments
  can/interfaces/gs_usb.py
  can/interfaces/nixnet.py
  test/__init__.py
  test/back2back_test.py
  test/config.py
  test/contextmanager_test.py
  test/data/__init__.py
  test/data/example_data.py
  test/listener_test.py
  test/logformats_test.py
  test/message_helper.py
  test/network_test.py
  test/notifier_test.py
  test/serial_test.py
  test/simplecyclic_test.py
  test/test_kvaser.py
Labels: minor

#1070 Repair Travis CI ARM setup
  .travis.yml
  test/back2back_test.py
Labels: QA, devops

#1071 Add bdist_wheel distribution to automated Travis CI deployment
  .travis.yml
Labels: devops

#1076 Specific Exceptions: Adapting neousys (+ bugfixes & simplifications)
  can/interfaces/neousys/neousys.py
  test/test_neousys.py
Labels: api, bug, enhancement

#966 Add msg direction for CAN-FD in BlfReader
  can/io/blf.py
  test/logformats_test.py
Labels: bug, file-io

#1036 Improve according to pylint
  .pylintrc
  can/broadcastmanager.py
  can/logger.py
  can/message.py
  can/player.py
  can/util.py
  can/viewer.py
Labels: QA, enhancement

#1086 Setting the transmit exception __cause__ to None
  can/interfaces/ics_neovi/neovi_bus.py
Labels: backend:neovi

#1094 Add new language classifiers to setup.py
  setup.py
Labels: docs, minor

#1095 Clean up pcan_test: Group imports and remove redundant one
  can/interfaces/pcan/__init__.py
  test/test_pcan.py
Labels: backend:pcan, minor

#1084 Typing annotations for VectorBus.__init__(...) are missing
  can/interfaces/vector/canlib.py
Labels: backend:vector, enhancement

#1092 Specific Exceptions: Adapting iscan interface (+ add typing)
  can/interfaces/iscan.py
Labels: backend:iscan, enhancement

#1089 Specific Exceptions: Adapting udp_multicast interface
  can/interfaces/udp_multicast/bus.py
  can/interfaces/udp_multicast/utils.py
Labels: backend:udp_multicast, enhancement

#1088 Specific Exceptions: Adapting serial interface
  can/interfaces/serial/serial_can.py
Labels: backend:serial, enhancement

#1087 Specific Exceptions: Adapting socketcan interface
  can/exceptions.py
  can/interfaces/socketcan/socketcan.py
  test/logformats_test.py
  test/test_cyclic_socketcan.py
Labels: backend:socketcan, enhancement

#1083 Specific Exceptions: Adapting vector interface
  can/interfaces/vector/__init__.py
  can/interfaces/vector/canlib.py
  can/interfaces/vector/exceptions.py
  can/interfaces/vector/xldriver.py
  test/test_vector.py
Labels: backend:vector, enhancement

#1085 Supress exception occuring in NIXNET _detect_available_configs()
  can/interfaces/nixnet.py
Labels: bug

#1077 Supress 'SystemError: DeviceNotFound' in cantact detect_available_configs()
  can/interfaces/cantact.py
Labels: bug
