Repository hardbyte/python-can, pull requests merged in 2021-04, with the labels that each got.

#942 Add test for VectorChannelConfig
  can/interfaces/vector/__init__.py
  test/test_vector.py
Labels: QA, backend:vector

#1003 Add supported Python implementations as badge
  README.rst
Labels: docs

#960 Add support for changing the loopback flag
  can/interfaces/socketcan/socketcan.py
  test/test_socketcan_loopback.py
Labels: api, backend:socketcan, enhancement

#1011 New wording for feature list in README
  README.rst
Labels: docs, minor

#1009 Remove AppVeyor since it is now redundant
  .appveyor.yml
  README.rst
  test/config.py
  test/test_message_sync.py
  tox.ini
Labels: devops

#1010 Improve code of serial interface
  can/bus.py
  can/interfaces/serial/serial_can.py
  can/message.py
  test/serial_test.py
Labels: backend:serial, bug

#1016 Fix a typo in serial docs
  doc/interfaces/serial.rst
Labels: backend:serial, docs

#1012 Add more typying
  .travis.yml
  can/broadcastmanager.py
  can/bus.py
  can/ctypesutil.py
  test/test_socketcan.py
Labels: QA

#1015 Add nanosecond resolution time stamping to socketcan
  can/interfaces/socketcan/constants.py
  can/interfaces/socketcan/socketcan.py
  doc/interfaces/socketcan.rst
Labels: backend:socketcan, enhancement, os:linux

#1023 Slightly refactor util.py
  can/typechecking.py
  can/util.py
  test/test_util.py
Labels: minor

#761 adding absolute timestamp to ASC reader
  can/io/asc.py
  test/data/test_CanMessage.asc
  test/logformats_test.py
Labels: enhancement, file-io

#1032 Simplify linting
  .pylintrc
  .pylintrc-wip
  .travis.yml
  can/broadcastmanager.py
  can/bus.py
  can/ctypesutil.py
  can/interface.py
  can/message.py
  can/notifier.py
  can/thread_safe_bus.py
  can/viewer.py
  test/network_test.py
  test/test_cantact.py
  test/test_kvaser.py
  test/test_message_class.py
  test/test_rotating_loggers.py
Labels: QA

#1031 Enable a tiny test case
  test/logformats_test.py
Labels: minor, testing

#1034 Catch time before 1970 in ASCReader
  can/io/asc.py
  tox.ini
Labels: bug, file-io

#1033 Add more type annotations
  .travis.yml
  can/bus.py
  can/interface.py
  can/io/blf.py
  can/io/generic.py
  can/io/logger.py
  can/io/player.py
  can/listener.py
  can/notifier.py
  can/thread_safe_bus.py
  examples/virtual_can_demo.py
  setup.cfg
Labels: QA, docs

#1026 Typos and formatting
  can/interfaces/nican.py
  doc/interfaces/ixxat.rst
Labels: minor
