Repository hardbyte/python-can, pull requests merged in 2022-12, with the labels that each got.

#1464 Tiny type narrowing
  can/interfaces/__init__.py
Labels: minor, work-in-progress

#1465 Improve interface registry: Fix DeprecationWarning + better typing + more robust
  can/interfaces/__init__.py
Labels: QA

#1463 PCAN: Fix Detection of Library on Windows on ARM
  can/interfaces/pcan/basic.py
Labels: bug, backend:pcan

#1467 Add conda badge and fix GHA badge
  README.rst
Labels: minor

#1472 Turn sphinx warnings into errors
  .github/workflows/ci.yml
  can/interfaces/nixnet.py
  doc/interfaces/nixnet.rst
Labels: docs, QA

#1471 Update pylint
  .github/workflows/ci.yml
  .gitignore
  .pylintrc
  can/bus.py
  can/interfaces/socketcan/socketcan.py
  can/interfaces/socketcan/utils.py
  can/io/asc.py
  can/io/blf.py
  can/io/canutils.py
  can/io/csv.py
  can/io/generic.py
  can/io/logger.py
  can/io/player.py
  can/io/printer.py
  can/io/sqlite.py
  can/io/trc.py
  can/listener.py
  can/logconvert.py
  can/logger.py
  can/message.py
  requirements-lint.txt
Labels: QA
