Repository hardbyte/python-can, pull requests merged in 2022-02, with the labels that each got.

#1249 Fix guaranteed crash when using usb2can
  can/interfaces/usb2can/usb2canInterface.py
Labels: bug, blocker

#1251 Update history & contributors
  CONTRIBUTING.md
  CONTRIBUTORS.txt
  doc/history.rst
Labels: docs

#1252 Pass flags instead of flags_t type for USB2CAN
  can/interfaces/usb2can/usb2canInterface.py
Labels: bug

#1246 [IO][ASC]: fix data length
  can/io/asc.py
  test/logformats_test.py
Labels: bug, file-io

#1257 ASCReader bugfix
  can/io/asc.py
  test/data/issue_1256.asc
  test/logformats_test.py
Labels: bug, file-io
