Repository hardbyte/python-can, pull requests merged in 2022-01, with the labels that each got.

#1197 [TINY] Fix syntax highlighting in bus.rst
  doc/bus.rst
Labels: minor, docs

#977 Fix vector get application config
  can/interfaces/vector/canlib.py
  test/test_vector.py
Labels: bug, backend:vector, work-in-progress

#1204 Add str conversion to config vals
  can/util.py
  test/test_util.py
Labels: bug

#1188 Implement check for minimum version of pcan library
  can/interfaces/pcan/pcan.py
  setup.py
  test/test_pcan.py
Labels: backend:pcan

#1215 [Tiny] Update README.rst
  README.rst
Labels: minor, docs

#1214 Update workflow versions, platforms, library and tool versions + README
  .github/workflows/build.yml
  .github/workflows/format-code.yml
  README.rst
  requirements-lint.txt
  setup.py
  tox.ini
Labels: QA

#1198 584 add test player
  test/data/logfile_errorframes.asc
  test/test_player.py
Labels: QA

#1218 Correct shebang and remove coding from all tests
  test/test_bit_timing.py
  test/test_cantact.py
  test/test_cyclic_socketcan.py
  test/test_detect_available_configs.py
  test/test_interface_ixxat.py
  test/test_interface_ixxat_fd.py
  test/test_load_file_config.py
  test/test_logger.py
  test/test_message_class.py
  test/test_message_filtering.py
  test/test_message_sync.py
  test/test_neousys.py
  test/test_robotell.py
  test/test_scripts.py
  test/test_slcan.py
  test/test_socketcan.py
  test/test_socketcan_helpers.py
  test/test_socketcan_loopback.py
  test/test_util.py
  test/test_vector.py
  test/test_viewer.py
  test/zero_dlc_test.py
Labels: QA

#1195 Add preserve timestamps to virtual
  can/interfaces/virtual.py
  doc/interfaces/virtual.rst
  test/test_interface_virtual.py
Labels: enhancement

#1216 Add changelog for 4.0.0
  CHANGELOG.md
  setup.py
Labels: docs

#1224 Move Static Code Analysis to Github Actions
  .github/workflows/build.yml
  .travis.yml
  can/ctypesutil.py
  can/exceptions.py
  can/io/asc.py
  can/io/blf.py
  can/io/canutils.py
  can/io/csv.py
  can/io/generic.py
  can/io/logger.py
  can/io/printer.py
  can/typechecking.py
  requirements-lint.txt
  setup.cfg
Labels: QA

#1223 Improve ASCReader robustness
  can/io/asc.py
  test/data/logfile.asc
  test/logformats_test.py
Labels: bug, file-io

#1228 Moderinze README code
  README.rst
Labels: minor, docs

#1221 1210 Add compressed file methods
  can/__init__.py
  can/io/__init__.py
  can/io/asc.py
  can/io/logger.py
  can/io/player.py
  test/data/test_CanMessage.asc.gz
  test/logformats_test.py
  test/test_logger.py
  test/test_player.py
Labels: bug, enhancement, blocker, api, file-io

#1229 Enable mypy for vector interface
  can/interfaces/vector/canlib.py
  can/interfaces/vector/xldriver.py
  setup.cfg
  test/test_vector.py
Labels: QA

#1232 Remove unnssesary conversion to list
  can/interfaces/__init__.py
Labels: minor

#1239 Address pylint issues
  can/broadcastmanager.py
  can/exceptions.py
  can/interface.py
  can/listener.py
  can/logconvert.py
  can/viewer.py
Labels: QA

#1233 Fix entry_points deprecation
  can/interfaces/__init__.py
Labels: QA

#1240 Update changelog
  CHANGELOG.md
Labels: docs
