Repository hardbyte/python-can, pull requests merged in 2022-11, with the labels that each got.

#1427 Fixing memory leak in neoVI bus where message_receipts grows with no limit
  can/interfaces/ics_neovi/neovi_bus.py
Labels: bug, backend:neovi

#1429 Add gzip check to compress method
  can/io/logger.py
Labels: bug, file-io

#1363 Update CHANGELOG for v4.1.0 release
  CHANGELOG.md
  can/__init__.py
Labels: docs

#1141 Ixxat bus state and hardware errors detection
  can/interfaces/ixxat/__init__.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/ixxat/canlib_vcinpl.py
  can/interfaces/ixxat/canlib_vcinpl2.py
  can/interfaces/ixxat/constants.py
  can/interfaces/ixxat/exceptions.py
  can/interfaces/ixxat/structures.py
Labels: backend:ixxat

#1443 Use furo html theme for documentation
  doc/conf.py
  doc/doc-requirements.txt
  doc/interfaces/vector.rst
Labels: docs

#1435 Add with statement to example in README.md
  README.rst
Labels: docs

#1447 Run pyupgrade --py37-plus
  can/interfaces/ics_neovi/neovi_bus.py
  can/interfaces/ixxat/canlib_vcinpl.py
  can/interfaces/ixxat/canlib_vcinpl2.py
  can/interfaces/ixxat/structures.py
  can/interfaces/kvaser/canlib.py
  can/interfaces/nixnet.py
  can/interfaces/pcan/basic.py
  can/interfaces/pcan/pcan.py
  can/interfaces/robotell.py
  can/interfaces/socketcan/socketcan.py
  can/interfaces/socketcan/utils.py
  can/interfaces/socketcand/socketcand.py
  can/interfaces/systec/ucanbus.py
  can/interfaces/vector/canlib.py
  can/io/canutils.py
  can/io/trc.py
  can/typechecking.py
  can/util.py
  can/viewer.py
  setup.py
  test/config.py
  test/listener_test.py
  test/logformats_test.py
  test/message_helper.py
  test/test_interface_virtual.py
  test/test_load_config.py
  test/test_load_file_config.py
  test/test_message_class.py
  test/test_message_sync.py
  test/test_viewer.py
Labels: QA

#1449 Use high resolution timer on Windows
  .github/workflows/ci.yml
  can/broadcastmanager.py
  setup.py
Labels: enhancement, os:windows
