Repository hardbyte/python-can, pull requests merged in 2022-03, with the labels that each got.

#1244 [IO][canutils]: add direction support
  can/io/canutils.py
  test/test_logger.py
Labels: enhancement, file-io

#1273 Fix BLF timestamp conversion
  can/io/blf.py
  test/logformats_test.py
Labels: bug

#1269 Fix channel2int conversion
  can/util.py
  test/test_util.py
Labels: bug

#1279 Update the black formatter to stable release
  can/interfaces/socketcan/constants.py
  can/interfaces/socketcan/socketcan.py
  can/interfaces/systec/ucan.py
  can/interfaces/vector/canlib.py
  requirements-lint.txt
  test/data/example_data.py
  test/network_test.py
Labels: QA

#1281 %d format is for a number, not str
  can/interfaces/neousys/neousys.py
Labels: backend:neousys
