Repository hardbyte/python-can, pull requests merged in 2022-08, with the labels that each got.

#1328 Detect types in _parse_additonal_config
  can/logger.py
  can/player.py
  can/viewer.py
  test/test_logger.py
Labels: bug, file-io

#1129 Finds USB2CAN Serial Number by USB Name
  can/interfaces/usb2can/serial_selector.py
Labels: enhancement, backend:usb2can

#1367 Add file_size() function to FileIOMessageWriter
  can/io/blf.py
  can/io/generic.py
  can/io/logger.py
  can/logger.py
Labels: api, file-io

#1366 Pass CLI extra_args to Logger initialisation
  can/io/asc.py
  can/io/blf.py
  can/io/canutils.py
  can/io/csv.py
  can/io/generic.py
  can/io/logger.py
  can/io/printer.py
  can/io/sqlite.py
  can/logger.py
  can/player.py
  can/viewer.py
Labels: file-io

#1374 Improve MessageSync timings
  can/io/player.py
  test/test_message_sync.py
  test/test_player.py
Labels: bug
