Repository hardbyte/python-can, pull requests merged in 2023-05, with the labels that each got.

#1580 Fix PCAN OSError
  can/interfaces/pcan/basic.py
Labels: bug, backend:pcan

#1590 With Windows event the first two periodic frames are sent without delay
  can/broadcastmanager.py
Labels: bug, os:windows

#703 Add auto-modifying cyclic tasks
  can/broadcastmanager.py
  can/bus.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/ixxat/canlib_vcinpl.py
  can/interfaces/ixxat/canlib_vcinpl2.py
  can/interfaces/socketcan/socketcan.py
  examples/cyclic_checksum.py
  test/simplecyclic_test.py
Labels: work-in-progress

#1599 Fix socketcan KeyError
  can/interfaces/socketcan/utils.py
  test/data/ip_link_list.json
  test/test_socketcan_helpers.py
Labels: bug, backend:socketcan

#1602 Activate ruff pycodestyle checks
  can/__init__.py
  can/interfaces/ixxat/canlib_vcinpl2.py
  can/interfaces/socketcan/socketcan.py
  can/interfaces/vector/canlib.py
  can/interfaces/vector/xldriver.py
  pyproject.toml
Labels: QA

#1603 Update linter instructions in development.rst
  doc/development.rst
Labels: docs

#1606 Fix IXXAT not properly shut down message
  can/interfaces/ixxat/canlib_vcinpl.py
  can/interfaces/ixxat/canlib_vcinpl2.py
Labels: bug, backend:ixxat
