Repository hardbyte/python-can, pull requests merged in 2023-03, with the labels that each got.

#1534 Update linters
  .pylintrc
  can/bus.py
  can/interface.py
  can/interfaces/__init__.py
  can/interfaces/ics_neovi/neovi_bus.py
  can/interfaces/iscan.py
  can/interfaces/pcan/basic.py
  can/interfaces/serial/serial_can.py
  can/interfaces/slcan.py
  can/interfaces/udp_multicast/bus.py
  can/interfaces/usb2can/usb2canInterface.py
  can/interfaces/virtual.py
  can/io/asc.py
  can/io/canutils.py
  can/io/csv.py
  can/io/logger.py
  can/io/player.py
  can/logconvert.py
  can/player.py
  can/thread_safe_bus.py
  examples/print_notifier.py
  examples/receive_all.py
  examples/send_one.py
  examples/serial_com.py
  examples/simple_log_converter.py
  examples/vcan_filtered.py
  requirements-lint.txt
  setup.py
  test/back2back_test.py
  test/serial_test.py
  test/simplecyclic_test.py
  test/test_pcan.py
  test/test_player.py
  test/test_util.py
Labels: QA

#1539 Improve ThreadBasedCyclicSendTask timing
  can/broadcastmanager.py
Labels: enhancement, os:windows

#1489 Add `__del__` method to `BusABC`
  can/bus.py
  can/interfaces/canalystii.py
  can/interfaces/etas/__init__.py
  can/interfaces/ixxat/canlib.py
  can/interfaces/socketcand/socketcand.py
  test/back2back_test.py
  test/test_bus.py
  test/test_interface.py
  test/test_interface_canalystii.py
Labels: bug, api
