Repository hardbyte/python-can, pull requests merged in 2024-08, with the labels that each got.

#1833 Test on Python 3.13
  .github/workflows/ci.yml
  can/broadcastmanager.py
  can/interfaces/usb2can/serial_selector.py
  can/io/trc.py
  can/notifier.py
  pyproject.toml
  test/network_test.py
  test/simplecyclic_test.py
  tox.ini
Labels: testing, QA

#1837 Undo #1772
  .github/workflows/ci.yml
  doc/conf.py
Labels: testing

#1838 Replace PyPy3.8 with PyPy3.10
  .github/workflows/ci.yml
  pyproject.toml
Labels: testing, PyPy

#1839 Add zlgcan to docs
  doc/plugin-interface.rst
  pyproject.toml
Labels: docs

#1847 Period must be >= 1ms for BCM using Win32 API
  can/broadcastmanager.py
Labels: bug
