Repository hardbyte/python-can, pull requests merged in 2024-06, with the labels that each got.

#1789 Return timestamps relative to epoch in neovi interface
  can/interfaces/ics_neovi/neovi_bus.py
Labels: enhancement, backend:neovi

#1794 Update linters and gh actions
  .github/workflows/ci.yml
  can/ctypesutil.py
  can/interfaces/ixxat/structures.py
  can/interfaces/kvaser/canlib.py
  can/interfaces/kvaser/structures.py
  can/interfaces/pcan/pcan.py
  can/interfaces/socketcan/socketcan.py
  can/interfaces/socketcand/socketcand.py
  can/interfaces/systec/exceptions.py
  can/interfaces/systec/ucanbus.py
  can/io/asc.py
  can/io/generic.py
  can/io/mf4.py
  can/io/player.py
  can/listener.py
  can/notifier.py
  can/typechecking.py
  can/util.py
  pyproject.toml
  test/test_rotating_loggers.py
Labels: QA

#1795 Remove abstractmethod() decorator from Listener.stop()
  can/listener.py
Labels: bug

#1496 Extented slcan.py to use "L" command optional to "O" command.
  can/interfaces/slcan.py
Labels: enhancement, backend:serial

#1793 Fix SizedRotatingLogger file format bug
  can/io/logger.py
  test/test_rotating_loggers.py
Labels: bug, file-io

#1800 Avoid logging socketcan exception on non-linux platforms
  can/interfaces/socketcan/utils.py
  test/test_socketcan_helpers.py
Labels: backend:socketcan

#1801 Fix PCAN test DeprecationWarnings
  test/test_pcan.py
Labels: QA

#1796 Activate channels after CAN filters were applied
  can/interfaces/kvaser/canlib.py
  can/interfaces/vector/canlib.py
Labels: bug, backend:kvaser, backend:vector

#1752 Add notes/kvaser support for non-iso support
  can/bus.py
  can/interfaces/kvaser/canlib.py
  doc/interfaces/pcan.rst
  doc/interfaces/socketcan.rst
  test/test_kvaser.py
Labels: backend:kvaser

#1804 Improve TestBusConfig
  can/util.py
  test/test_util.py
Labels: testing

#1805 Refactor CLI filter parsing, add tests
  can/logger.py
  can/typechecking.py
  can/viewer.py
  doc/other-tools.rst
  doc/scripts.rst
  test/test_logger.py
  test/test_viewer.py
Labels: QA

#1806 Resolve AttributeError within NicanError
  can/interfaces/nican.py
Labels: bug, backend:nican
