Repository hardbyte/python-can, pull requests merged in 2025-03, with the labels that each got.

#1851 CC-2174: modify CAN frame header structure to match updated struct ca…
  can/interfaces/socketcan/constants.py
  can/interfaces/socketcan/socketcan.py
Labels: backend:socketcan

#1927 Fix float arithmetic in BLF reader
  can/io/blf.py
  test/logformats_test.py
Labels: bug, file-io

#1929 Update black, ruff & mypy
  can/__init__.py
  can/bit_timing.py
  can/broadcastmanager.py
  can/bus.py
  can/ctypesutil.py
  can/interface.py
  can/interfaces/ics_neovi/__init__.py
  can/interfaces/ixxat/canlib_vcinpl.py
  can/interfaces/ixxat/canlib_vcinpl2.py
  can/interfaces/ixxat/exceptions.py
  can/interfaces/ixxat/structures.py
  can/interfaces/kvaser/__init__.py
  can/interfaces/neousys/__init__.py
  can/interfaces/neousys/neousys.py
  can/interfaces/pcan/__init__.py
  can/interfaces/seeedstudio/__init__.py
  can/interfaces/serial/__init__.py
  can/interfaces/slcan.py
  can/interfaces/socketcan/utils.py
  can/interfaces/usb2can/__init__.py
  can/interfaces/usb2can/serial_selector.py
  can/interfaces/vector/__init__.py
  can/interfaces/vector/canlib.py
  can/io/__init__.py
  can/io/blf.py
  can/io/canutils.py
  can/io/generic.py
  can/io/logger.py
  can/io/mf4.py
  can/io/printer.py
  can/message.py
  can/player.py
  can/typechecking.py
  can/util.py
  can/viewer.py
  pyproject.toml
  test/listener_test.py
  test/test_interface_canalystii.py
  test/test_kvaser.py
  test/test_neovi.py
  test/test_vector.py
  test/zero_dlc_test.py
Labels: QA
